### ISSUE TITLE
Board Service 구현

### ISSUE THREAD

**Issue by byallfine01** [GoOnThat/GoOnThat-Backend#13]
## Description
* Board Service 개발 
---
## 주요 서비스 로직
위 Service 종류 중 Application 일 경우 주요 서비스 로직을 작성해주세요.  
(추후 업데이트 예정)
## 주요 비즈니스 로직
위 Service 종류 중 Domain 일 경우 주요 서비스 로직을 작성해주세요.

예시)

1. 게시판 목록 조회 로직
2. 게시판 글 상세 조회 로직
3. 글 등록 로직
4. 글 수정 로직
5. 글 삭제 로직

---

## 주요 메서드
- selectBoardList - 게시판 전체 조회
- selectBoardDatail - 게시판 글 세부 조회
- insertBoard - 글 등록
- updateBoard - 글 수정
- deleteBoard - 글 삭제

---

## TODO
- [ ]  DTO 연계 작성
- [ ]  CRUD 구현

---

## ETC

---
* CRUD 중 select는 마이바티스 사용
* 나머지는 JPA 사용예정

**Additional context**

**Comment by devJaem** [comment]
07.20 완료함
